### ISSUE TITLE
Could not compile it

### ISSUE THREAD

**Issue by chernogorsky** [Civil/ch-flamegraphs#1]
Hi,
Im trying to install it 
but have several issue during compile

cd $GOROOT
go get github.com/Civil/ch-flamegraphs
cd ${GOPATH}/src/github.com/Civil/ch-flamegraphs
make

1st issue
./main.go:207:31: cannot use cluster (type string) as type int64 in argument to sender.SendMetricStats
./main.go:207:31: cannot use id (type uint64) as type string in argument to sender.SendMetricStats

can be fixed by replacing
err = sender.SendMetricStats(cluster, path, id, data.ModTime, data.ATime, data.RdTime, 1)
err = sender.SendMetricStats(t, cluster, path, data.ModTime, data.ATime, data.RdTime, 1)

2nd
make[1]: Entering directory `/opt/go/go-git/gopath/src/github.com/Civil/ch-flamegraphs/cmd/flamegraph-server'
go build --ldflags '-X main.BuildVersion=8b19-dirty'
# github.com/Civil/ch-flamegraphs/cmd/flamegraph-server
./main.go:430:7: cannot use res.Id (type uint64) as type int64 in map index
./main.go:434:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:435:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:436:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:437:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:438:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:440:20: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:444:34: cannot use "github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".RootElementId (type uint64) as type int64 in map index
./main.go:447:24: cannot use data (type map[int64]"github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".ClickhouseField) as type map[uint64]"github.com/Civil/ch-flamegraphs/vendor/github.com/Civil/carbonserver-flamegraphs/types".ClickhouseField in argument to helper.ReconstructTree

My knowledge (lack of it) of Go does not allow me to solve it by my own

**Comment by Civil** [comment]
I've pushed a fix, it should build now ok. I think I broke it by accident while fixing application profile receiver.

I haven't checked though if clickhouse schema (hardcoded one) have correct types now. Please reopen if it's not

**Comment by Civil** [comment]
https://github.com/Civil/ch-flamegraphs/commit/43c032d7de7d3bdda6480aca635ce38f0ed90eb2 - this commit also fixes schema creation. I hope all components will work now.

**Comment by chernogorsky** [comment]
thanks. it works. (or at least I could compile it) trying to make it show me something.
